// <auto-generated />
using System;
using CkBotMaster.AuditBot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CkBotMaster.AuditBot.Data.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    [Migration("20260501145105_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ckbotmaster")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CkBotMaster.AuditBot.Data.Entities.AuditEntry", b =>
                {
                    b.Property<decimal>("DiscordEntryId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("ActorId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FromCatchup")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("ReasonStatus")
                        .HasColumnType("integer");

                    b.Property<string>("ReasonText")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("DiscordEntryId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("audit_entries", "ckbotmaster");
                });

            modelBuilder.Entity("CkBotMaster.AuditBot.Data.Entities.BotState", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Key");

                    b.ToTable("bot_state", "ckbotmaster");
                });

            modelBuilder.Entity("CkBotMaster.AuditBot.Data.Entities.PendingReason", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ActorId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("AuditEntryId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PromptChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("PromptMessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("PromptMode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuditEntryId");

                    b.HasIndex("ActorId", "IsOpen");

                    b.HasIndex("IsOpen", "ExpiresAt");

                    b.ToTable("pending_reasons", "ckbotmaster");
                });

            modelBuilder.Entity("CkBotMaster.AuditBot.Data.Entities.PendingReason", b =>
                {
                    b.HasOne("CkBotMaster.AuditBot.Data.Entities.AuditEntry", "AuditEntry")
                        .WithMany()
                        .HasForeignKey("AuditEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditEntry");
                });
#pragma warning restore 612, 618
        }
    }
}
